[project]
name = "netwatch-cli"
version = "1.1.0"
description = "Linux Network Monitoring Tool"
requires-python = ">=3.10"

dependencies = [
    "rich",
    "ping3",
    "psutil",
    "manuf"
]

[project.scripts]
netwatch = "netwatch.cli:main"

[tool.setuptools.packages.find]
include = ["netwatch*"]
